version: '3.8'

services:
  app:
    container_name: app-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${APP_PORT}:${APP_PORT}'
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
  db:
    container_name: app-db-service
    image: 'postgres:14.1-alpine'
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
